"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-change-me-in-production'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Keycloak (hardcoded per requirement)
KEYCLOAK_URL = 'https://sso-pmpa-hom.procempa.com.br/auth'
KEYCLOAK_REALM = 'pmpa'
KEYCLOAK_CLIENT_ID = 'geoteste'
REQUIRED_ROLE = 'mcp'

# Allow small clock drift between this server and Keycloak.
# Helps avoid intermittent "Token not yet valid (nbf/iat)".
KEYCLOAK_CLOCK_SKEW_SECONDS = int(os.getenv('KEYCLOAK_CLOCK_SKEW_SECONDS', '60'))

# Frontend URL (used by Django Admin "View site")
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:80')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authentication.apps.AuthenticationConfig',
    'corsheaders',
    'django.contrib.gis',  # GeoDjango
    'layers_geoserver',
    'address_search',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'authentication.middleware.KeycloakRequiredMiddleware',
    'authentication.logging_middleware.RequestLogContextMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

# Optional Postgres schema (e.g. "mcp"). If set, Django will use it as the
# first schema in the search_path, while keeping "public" as fallback.
DB_SCHEMA = (os.getenv('DB_SCHEMA') or '').strip()
if DB_SCHEMA:
    DATABASES['default'].setdefault('OPTIONS', {})
    # Ensure our search_path takes precedence but still allows PostGIS/public extensions.
    DATABASES['default']['OPTIONS']['options'] = f"-c search_path={DB_SCHEMA},public"


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Upload limits
# Values are in bytes.
# DATA_UPLOAD_MAX_MEMORY_SIZE caps total request size; keep it aligned with your maximum allowed upload.
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('DJANGO_DATA_UPLOAD_MAX_MEMORY_SIZE', str(50 * 1024 * 1024)))  # 50 MB
# FILE_UPLOAD_MAX_MEMORY_SIZE controls when Django spills upload buffers to temp files (not a total size cap).
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('DJANGO_FILE_UPLOAD_MAX_MEMORY_SIZE', str(10 * 1024 * 1024)))  # 10 MB

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# GeoServer
GEOSERVER_BASE_URL = os.getenv('GEOSERVER_BASE_URL', '')
GEOSERVER_USER = os.getenv('GEOSERVER_USER', '')
GEOSERVER_PASSWORD = os.getenv('GEOSERVER_PASSWORD', '')

# Windows specific configuration for GDAL if needed
if os.name == 'nt':
    import platform
    # This is a placeholder. On Windows, you often need to set GDAL_LIBRARY_PATH
    # or ensure OSGeo4W is in the path as per the documentation provided.
    pass


# Logging: include preferred_username (or Django username) in access logs.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'add_kc_user': {
            '()': 'authentication.logging_filters.AddPreferredUsernameFilter',
        },
    },
    'formatters': {
        'django.server.with_user': {
            '()': 'django.utils.log.ServerFormatter',
            'format': '[{server_time}] ({kc_user}) {message}',
            'style': '{',
        },
        'audit.with_user': {
            'format': '[{asctime}] ({kc_user}) AUDIT {message}',
            'style': '{',
        },
    },
    'handlers': {
        'django.server': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stdout',
            'formatter': 'django.server.with_user',
            'filters': ['add_kc_user'],
        },
        'audit': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stdout',
            'formatter': 'audit.with_user',
            'filters': ['add_kc_user'],
        },
    },
    'loggers': {
        'django.server': {
            'handlers': ['django.server'],
            'level': 'INFO',
            'propagate': False,
        },
        'mcp.audit': {
            'handlers': ['audit'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
